version: '3.3'
     
services:
  web:
    build: ./app
    command: sh run.sh
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      ./.env.dev
    ports:
      - 9090:9090
    depends_on:
      - postgres
  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      ./.env.db

volumes:
  postgres_data: